### ISSUE TITLE
Height declaration not working

### ISSUE THREAD

**Issue by Ivanverdonck** [tfohlmeister/eink-display-server#1]
Hi,

There is an error in the "Environmental Variable" declaration:
The "height" is not copied correctly.

`const EINK_WIDTH = Number(process.env.EINK_WIDTH) || 800;
const EINK_HEIGHT = Number(process.env.EINK_WIDTH) || 480;`

Kind regards,
Ivan.

**Comment by tfohlmeister** [comment]
Thanks for pointing this out! I will fix it ASAP!

**Comment by tfohlmeister** [comment]
Fixed in v1.2.4
